#!/usr/bin/env sh
# preflight.sh — detect reverse-engineering tools; emit install.sh + Dockerfile.snippet.
# NEVER installs anything. POSIX sh; Linux + macOS. Usage: preflight.sh [OUTPUT_DIR]
set -eu

OUT="${1:-.}"; mkdir -p "$OUT"
INSTALL="$OUT/install.sh"; DOCKER="$OUT/Dockerfile.snippet"
VENV="${RE_HARNESS_VENV:-$HOME/.local/share/re-harness/venv}"
PYBIN="$VENV/bin/python"; [ -x "$PYBIN" ] || PYBIN=python3

case "$(uname -s 2>/dev/null || echo unknown)" in
  Linux)  APT="sudo apt-get install -y" ;;
  Darwin) APT="brew install" ;;
  *)      APT="# install via your package manager:" ;;
esac

# Registry: cmd|purpose|apt_pkg|pip_pkg   (pip_pkg set => detect as python module)
REG="$(mktemp)"; trap 'rm -f "$REG"' EXIT
cat > "$REG" <<'EOF'
file|identify file type & format|file|
strings|extract strings (binutils)|binutils|
objdump|disassembly (binutils)|binutils|
readelf|ELF inspection (binutils)|binutils|
nm|symbol listing (binutils)|binutils|
xxd|hex dump|xxd|
binwalk|firmware extraction & entropy|binwalk|
radare2|disassembly & analysis|radare2|
gdb|dynamic debugging|gdb|
ltrace|library-call tracing|ltrace|
strace|syscall tracing|strace|
upx|(un)packing UPX binaries|upx-ucl|
python3|scripting runtime|python3|
angr|symbolic execution (python)|python3-pip|angr
z3|SMT solver (python)|python3-pip|z3-solver
EOF

printf '%-10s %-6s %s\n' TOOL FOUND PURPOSE
printf '%-10s %-6s %s\n' ---------- ------ -------------------------------

MISS_APT=""; MISS_PIP=""
while IFS='|' read -r cmd purpose apt pip; do
  [ -z "${cmd:-}" ] && continue
  case "$cmd" in
    angr) "$PYBIN" -c 'import angr' >/dev/null 2>&1 && found=yes || found=no ;;
    z3)   "$PYBIN" -c 'import z3'   >/dev/null 2>&1 && found=yes || found=no ;;
    *)    command -v "$cmd" >/dev/null 2>&1 && found=yes || found=no ;;
  esac
  printf '%-10s %-6s %s\n' "$cmd" "$found" "$purpose"
  if [ "$found" = no ]; then
    if [ -n "$pip" ]; then MISS_PIP="$MISS_PIP $pip"
    elif [ -n "$apt" ]; then MISS_APT="$MISS_APT $apt"; fi
  fi
done < "$REG"

# de-duplicate
MISS_APT="$(printf '%s\n' $MISS_APT | sort -u | tr '\n' ' ')"
MISS_PIP="$(printf '%s\n' $MISS_PIP | sort -u | tr '\n' ' ')"

# ---- install.sh (copy-paste; user runs it themselves) ----
{
  echo '#!/usr/bin/env sh'
  echo '# Generated by re-preflight. REVIEW before running. Installs MISSING tools only.'
  echo 'set -eu'
  [ -n "$(echo "$MISS_APT" | tr -d ' ')" ] && { echo '# system packages:'; echo "$APT $MISS_APT"; }
  [ -n "$(echo "$MISS_PIP" | tr -d ' ')" ] && { echo '# python tools (uv venv — see requirements/setup.sh):'; echo "uv venv \"$VENV\""; echo "uv pip install --python \"$VENV/bin/python\" $MISS_PIP"; }
  echo '# Ghidra (manual — not an apt package): install a JDK 17+, then:'
  echo '#   download from https://github.com/NationalSecurityAgency/ghidra/releases'
  echo '#   unzip, then add ghidra_*/support to PATH (provides analyzeHeadless).'
} > "$INSTALL"
chmod +x "$INSTALL"

# ---- Dockerfile.snippet (paste into a Dockerfile) ----
{
  echo '# --- RE tools (generated by re-preflight) ---'
  [ -n "$(echo "$MISS_APT" | tr -d ' ')" ] && echo "RUN apt-get update && apt-get install -y $MISS_APT"
  [ -n "$(echo "$MISS_PIP" | tr -d ' ')" ] && echo "RUN uv pip install --python \"\$RE_HARNESS_VENV/bin/python\" $MISS_PIP   # see requirements/Dockerfile"
  echo '# Ghidra: needs a JDK + manual download; e.g.'
  echo '#   RUN apt-get install -y openjdk-17-jdk unzip wget \'
  echo '#    && wget -O /tmp/ghidra.zip <release-url> && unzip /tmp/ghidra.zip -d /opt'
  echo '#   ENV PATH="/opt/ghidra_VER/support:$PATH"'
} > "$DOCKER"

echo
echo "Wrote: $INSTALL"
echo "Wrote: $DOCKER"
echo "re-preflight never installs anything; review and run install.sh yourself."
